### ISSUE TITLE
log ip

### ISSUE THREAD

**Issue by HyperSin** [huludini/pw-web#25]
i was thinking if possible , log the ip of registering users and when they login panel with the account if there ip was changed have it automatically update it, just an idea

factions still dont work

**Comment by BahaStriker** [comment]
Many features are missing and the way the panel is coded it really hard to mess with unless you really really know what you're doing.. All my attempts to change something comes mostly to fail and shows "Whoops, looks like something went wrong." 

The issue is that I'm using the panel on a live server that actually have 200 players online daily and they keep complaining on the missing stuff and other few stuff 

but what pissing me off the most is the proxy voting because the panel doesn't check the user IP + ID for voting record, it only checks for IP address.. Same goes for Voucher it only checks for ID and not IP address..

I started working on my own version now with pure PHP without any complications or Laravel

here's few mods I worked on that actually works for now 

Faction icon -> http://prntscr.com/andinh
Gift Panel points -> http://prntscr.com/andj7a
http://prntscr.com/andmli
Vote -> http://prntscr.com/andmrp
http://prntscr.com/andn6d
Still working on others though 

I guess Hulu is busy working on Aura Kingdom's panel and forgot about Perfect World, can't blame him though

**Comment by HyperSin** [comment]
Hulu is a great guy, he codes excellent work, he just needs people to help him out, i haven't had much problems out of it, nothing missing in my eyes

**Comment by BahaStriker** [comment]
I know he is, I wouldn't support the project otherwise. 
His coding is well organized but to be honest I'm in Perfect World development for less than a year, I basically know nothing from the little that the community knows, though I'm still running a server because I found it interesting.. I learned PHP along the way and I'm willing to learn Laravel to see how this thing actually works and I might fix few things 
I already made these 2 functions in Hulu's panel and I will gladly post the codes here if people requests it 
http://prntscr.com/ane75u

as for the topic, I'm already looking trying to figure it how to log users IP address because Payment Wall is requesting the user's registration IP and their current IP

**Comment by HyperSin** [comment]
do they work and can you make a reawakening on 1-10

**Comment by tomirons** [comment]
I don't know the deal with the factions, and I have way to much stuff on my plate to try to deal with it. I thought I released an update with the IP check in them, I'll look that up later.

Laravel is so easy to learn! It was tough to get setup, but once you get the feel for it you can do ANYTHING!

**Comment by BahaStriker** [comment]
> do they work and can you make a reawakening on 1-10

Yes they work perfectly, for reawakening I can do that if you tell me which line in character XML mode controls it because I never worked with reawakening before.

add me on Skype `baha.calas` if you need any help in PW wise I'd gladly help you

**Comment by HyperSin** [comment]
"reincarnation_data":
